# Étape 1 : Choisir l'image de base
FROM node:14

# Étape 2 : Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Étape 3 : Copier les fichiers de configuration dans le conteneur
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier le contenu du dossier "app" dans le conteneur
COPY ./app ./app

# Étape 6 : Exposer le port sur lequel l'application tourne (ajustez-le si nécessaire)
EXPOSE 3000

# Étape 7 : Commande de démarrage de l'application
CMD ["npm", "start"]
